-- R.O - Gestao de Reclamacoes da Qualidade: enums.
-- As listas vem das validacoes da planilha
-- "especificacao_controle_reclamacoes_qualidade.xlsx".

-- O R.O entra como o 8o modulo da grade de acesso.
ALTER TYPE "ModuloSistema" ADD VALUE IF NOT EXISTS 'RO';

DO $$ BEGIN
  CREATE TYPE "CompletudeSacRo" AS ENUM ('SIM', 'NAO', 'PARCIAL');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "AceiteRo" AS ENUM ('SIM', 'NAO', 'AGUARDANDO');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "SimNaoRo" AS ENUM ('SIM', 'NAO');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "ClassificacaoRo" AS ENUM (
    'DEFEITO_FUNCIONAL', 'FALHA_DESEMPENHO', 'PROBLEMA_DIMENSIONAL',
    'MATERIAL_INCORRETO', 'QUANTIDADE_INCORRETA', 'EMBALAGEM', 'DOCUMENTACAO',
    'MONTAGEM_INSTALACAO', 'SOFTWARE_COMUNICACAO', 'ENTREGA_LOGISTICA',
    'SEGURANCA', 'BEM_ESTAR_ANIMAL', 'MEIO_AMBIENTE', 'OUTRO'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "ProcedenciaRo" AS ENUM (
    'PROCEDENTE', 'PARCIALMENTE_PROCEDENTE', 'NAO_PROCEDENTE', 'INCONCLUSIVA'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "AreaResponsavelRo" AS ENUM (
    'QUALIDADE_PRODUCAO', 'SQE', 'SQD', 'ENGENHARIA', 'LOGISTICA',
    'SERVICO_ASSISTENCIA', 'EQUIPE_MULTIFUNCIONAL'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "PrioridadeRo" AS ENUM ('CRITICA', 'ALTA', 'MEDIA', 'BAIXA');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "MetodoAnaliseRo" AS ENUM (
    'CINCO_PORQUES', 'ISHIKAWA', 'PARETO', 'FMEA', 'OITO_D',
    'TESTE_REPRODUCAO', 'ANALISE_DADOS', 'AUDITORIA', 'OUTRO'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "StatusAcaoRo" AS ENUM (
    'NAO_INICIADA', 'EM_ANDAMENTO', 'CONCLUIDA', 'ATRASADA', 'CANCELADA'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "EficaciaRo" AS ENUM (
    'EFICAZ', 'PARCIALMENTE_EFICAZ', 'INEFICAZ', 'NAO_APLICAVEL'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "MotivoEncerramentoRo" AS ENUM (
    'PROCEDENTE_COM_ACAO', 'NAO_PROCEDENTE', 'DUPLICADA', 'CANCELADA',
    'INCONCLUSIVA'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "StatusRo" AS ENUM (
    'RECEBIDA_SAC', 'EM_TRIAGEM', 'AGUARDANDO_SAC', 'DIRECIONADA', 'CONTENCAO',
    'INVESTIGACAO', 'ACOES_CORRETIVAS', 'AGUARDANDO_EFICACIA', 'RETORNO_SAC',
    'ENCERRADA', 'REABERTA', 'NAO_ACEITA'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "TipoTarefaRo" AS ENUM ('CONTENCAO', 'ACAO_CORRETIVA');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
